### ISSUE TITLE
Show error message on screen, if no config.js exists

### ISSUE THREAD

**Issue by ErdnussFlipS** [TouchTheBeat/TouchTheBeat#70]
If you start the game without a config.js, there is a blank screen.
The user should be notified, that no config exists. Currently there is only a console log for that.

The error message could be similar to the "Not connected to backend" message.

**Comment by hstolte** [comment]
Since ``config.js`` is a ``RequireJS-module``, the actual TouchTheBeat javascript code does not even get executed in case the ``config.js`` file does not exist. The error message component that is also used for displaying the "Not connected to backend" message is a ``RequireJS-module`` itself and therefore cannot be used when the dependency loading fails. 

Because I think it is not a high priority issue right now and the simplest solution would not work, I will not implement this right now.

**Comment by hstolte** [comment]
I found a simple solution for showing an error message on the screen. 
It is possible to use an error callback as follows:
````javascript
requirejs.onError = function (error) {
    // error handling
};
````
The ``error`` object (first parameter) contains information on the requirejs error and the associated modules.
